name: dart_mercure
description: A library to communicate with dunglas/mercure. This library allow publish and subscribe on Mercure Hub. It can be easily integrate with other package for create firebase like notification system.
version: 0.1.1
homepage: https://gitlab.com/wallforfry/dart_mercure
author: Wallerand DELEVACQ <wallforfry@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  eventsource: ^0.2.2
  http: ^0.12.0+2
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
