name: Dart CI

on:
  push: ~
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    services:
      mercure:
        image: dunglas/mercure:latest
        env:
          JWT_KEY: '!ChangeMe!'
        ports:
          - 80:80

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
      - name: Dart/Flutter Package Analyzer
        uses: axel-op/dart-package-analyzer@v2.0.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
